# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51cbb69c4bd93e328becdcbb25ac801dc92ef2469e0a843bea8c146882fe5a15d36e4accfc10c0c64217dfec2c75851f3cdfaab1640b73186b691bf5515bf454

test:
  secret_key_base: ef428688363d94236248cd6f13ab851ebcb555060f85838cd16f568d5184e35d37bac2ff2236e1edf07e5122551038afcd559f5bfaa79c7949261c2b7d510873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
